schemaVersion: "0.0.1"
kind: "studio-config"
session:
    description: "A studio image built from a Dockerfile in a git repository."
    template:
        kind: "dockerfile"
        dockerfile: "Dockerfile"
