schemaVersion: "0.0.1"
kind: "studio-config"
session:
    name: "studio-example"
    description: "A VS Code studio configured from git repository."
    template:
        kind: "registry"
        registry: "public.cr.seqera.io/platform/data-studio-vscode:1.101.2-0.9"
